### ISSUE TITLE
ImportError: No module named ee

### ISSUE THREAD

**Issue by r-barnes** [ChHarding/TouchTerrain_for_CAGEO#2]
Upon running `TouchTerrain_standalone.py` with Python2.7, I get this error:

```
Traceback (most recent call last):
  File "TouchTerrain_standalone.py", line 85, in <module>
    import config # this needs to be set up for your dev account and needs a .pem file
  File "/z/TouchTerrain_for_CAGEO/config.py", line 5, in <module>
    from ee import oauth
ImportError: No module named ee
```

**Comment by ChHarding** [comment]
Hi Richard,


The ReadMe.md file does not give users a very good idea about which of 7 python files to run, or what they do. Configuration is apparently necessary, but not well-described by the realm.

Very true, since I wrote this we’ve change from a Google app engine dev server to and apache server. Our server guy has a script that bootstraps everything for the apache server version, but I need to do something similar for the stand alone version. I’ll wipe my existing setup and will start from scratch and keep track what i installed/ configured. I _think_ it’s primarily the installation of the Google App Engine Python and the Google Earth Engine (ee) package but you will also need to get a free google developers (or service)  account so that you can authenticate to Google Earth Engine.

Traceback (most recent call last):
  File "TouchTerrain_standalone.py", line 85, in <module>
    import config # this needs to be set up for your dev account and needs a .pem file
  File "/z/TouchTerrain_for_CAGEO/config.py", line 5, in <module>
    from ee import oauth
ImportError: No module named ee
It’s missing the ee (Google Earth Engine) module but even if you had it installed you will still need the have an account and you also need to generate that pen key file:

(from config.py):

# The service account email address authorized by your Google contact.
# Set up a service account as described here:
# https://sites.google.com/site/earthengineapidocs/creating-oauth2-service-account
EE_ACCOUNT = 'your-service-account-id@developer.gserviceaccount.com'
# The private key associated with your service account in Privacy Enhanced
# Email format (.pem suffix). To convert a private key from the RSA format
# (.p12 suffix) to .pem, run the openssl command like this:
# openssl pkcs12 -in downloaded-privatekey.p12 -nodes -nocerts > privatekey.pem
EE_PRIVATE_KEY_FILE = 'privatekey.pem'

(Again, I’ll add a better instructions for this later …)

Running TouchTerrain_standalone.py gives the message:

Wrote example_config.json with default value, use it as a template but make sure to rename it!
But the file example_config.json does not appear to exist.



There’s an example_config.json file in the main folder:  https://github.com/ChHarding/TouchTerrain_for_CAGEO/blob/master/example_config.json <https://github.com/ChHarding/TouchTerrain_for_CAGEO/blob/master/example_config.json>

but if not it gets created by TouchTerrain_standalone.py in the same folder.
The way to use this is to edit example_config.json with your own settings and save it with a different name (say to bla.json) and then run the script with it:

python  TouchTerrain_standalone.py bla.json

Right now that won’t work for you as the script bails out early b/c you don’t have ee installed and configured but I’ll get on that ASAP.


Cheers

Chris
